---
 - name: Add signing key
   ansible.builtin.rpm_key:
     key: https://download.docker.com/linux/centos/gpg
     state: present

 - name: Add repository
   ansible.builtin.yum_repository:
     name: docker
     description: Docker Repository
     baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
     enabled: true
     gpgcheck: true
     gpgkey: https://download.docker.com/linux/centos/gpg

 - name: Epel
   ansible.builtin.yum:
     name:
       - epel-release

 - name: Install Docker
   ansible.builtin.yum:
     name:
       - docker-ce
       - docker-ce-cli
       - containerd.io
       - python3-docker
     state: latest
     update_cache: true

 - name: Enable docker
   ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
    masked: no

 - name: Create docker directories
   ansible.builtin.file:
     path: "{{ item }}"
     state: directory
     mode: 0755
   loop:
     - "{{ build_dir_path }}"
     - "{{ build_dir_path }}/gitlab"

 - name: Create gitlab container
   community.docker.docker_container:
     name: gitlab
     image: gitlab/gitlab-ce
     state: started
     shm_size: 256m
     domainname: "gitlab.{{ domain_name }}"
     dns_servers: "{{ dns_servers }}"
     restart_policy: always
     volumes:
       - "{{ build_dir_path }}/gitlab/config:/etc/gitlab"
       - "{{ build_dir_path }}/gitlab/data:/var/opt/gitlab"
     ports:
       - "{{ docker_bridge_if }}:122:22"
       - "{{ docker_bridge_if }}:{{ web_port_gitlab }}:80"
       - "{{ docker_bridge_if }}:1443:443"

 - name: Generate freeipa client yml
   ansible.builtin.template:
     src: freeipa_client_gitlab.j2
     dest: "{{ build_dir_path }}/gitlab/config/freeipa_client.yml"
     owner: root
     group: root
     mode: 0644
   register: current_ipa_auth_conf

 - name: Kostylyk(next file appears not in moment)
   ansible.builtin.wait_for:
     path: "{{ build_dir_path }}/gitlab/config/gitlab.rb" 

 - name: Add lines to gitlab config
   ansible.builtin.blockinfile:
     path: "{{ build_dir_path }}/gitlab/config/gitlab.rb"
     block: |
       gitlab_rails['ldap_enabled'] = true
       gitlab_rails['ldap_servers'] = YAML.load_file('/etc/gitlab/freeipa_client.yml')
       gitlab_rails['smtp_enable'] = true
       gitlab_rails['smtp_address'] = "{{ docker_bridge_if }}"
       gitlab_rails['smtp_port'] = 25
       gitlab_rails['smtp_domain'] = "{{ smtp_server_name }}.{{ domain_name }}"
       gitlab_rails['smtp_authentication'] = "login"
       gitlab_rails['gitlab_email_from'] = "gitlab@{{ domain_name }}"
       gitlab_rails['gitlab_email_reply_to'] = "noreply@{{ domain_name }}"
   register: current_gitlab_rb

 - name: Restart a container
   community.docker.docker_container:
     name: gitlab
     image: gitlab/gitlab-ce
     state: started
     restart: yes
   when: current_gitlab_rb.changed or current_ipa_auth_conf.changed 

 - name: Create user for auth in FREEIPA
   freeipa.ansible_freeipa.ipauser:
     ipaadmin_password: "{{ ipaadmin_password }}"
     name: "{{ free_ipa_client }}"
     first: "{{ free_ipa_client }}"
     last: "{{ free_ipa_client }}"
     password: "{{ free_ipa_password }}"
     update_password: on_create
