---

 - name: Enable repository
   ansible.builtin.shell:
     cmd: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
     warn: false

 - name: install Docker
   ansible.builtin.dnf:
     name:
       - docker-ce
       - python3
       - python3-pip
     state: latest
 
 - name: Install docker python package
   ansible.builtin.pip:
     name: docker

 - name: Enable docker
   ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
    masked: no

 - name: Create docker directories
   ansible.builtin.file:
     path: "{{ item }}"
     state: directory
     mode: '0755'
   loop:
     - "{{ build_dir_path }}"
     - "{{ build_dir_path }}/gitlab"
     - "{{ build_dir_path }}/nexus"


 - name: Create gitlab container
   community.docker.docker_container:
     name: gitlab
     image: gitlab/gitlab-ce
     state: started
     shm_size: 256m
     domainname: "gitlab.{{ domain_name }}"
     dns_servers: "{{ dns_servers }}"
     restart_policy: always
     volumes:
       - "{{ build_dir_path }}/gitlab/config:/etc/gitlab"
       - "{{ build_dir_path }}/gitlab/logs:/var/log/gitlab"
       - "{{ build_dir_path }}/gitlab/data:/var/opt/gitlab"
     ports:
       - "122:22"
       - "180:80"
       - "1443:443"


 - name: Generate freeipa client yml
   ansible.builtin.template:
     src: "freeipa_client_gitlab.j2"
     dest: "{{ build_dir_path }}/gitlab/config/freeipa_client.yml"
     owner: "root"
     group: "root"
     mode: "0644"
   register: current_ipa_auth_conf

 - name: Kostylyk(next file appears not in moment)
   ansible.builtin.wait_for:
     path: "{{ build_dir_path }}/gitlab/config/gitlab.rb" 

 - name: Add lines to gitlab config
   ansible.builtin.blockinfile:
     path: "{{ build_dir_path }}/gitlab/config/gitlab.rb"
     block: |
       gitlab_rails['ldap_enabled'] = true
       gitlab_rails['ldap_servers'] = YAML.load_file('/etc/gitlab/freeipa_client.yml')
       gitlab_rails['smtp_enable'] = true
       gitlab_rails['smtp_address'] = "172.17.0.1"
       gitlab_rails['smtp_port'] = 25
       gitlab_rails['smtp_domain'] = "example.com"
       gitlab_rails['smtp_authentication'] = "login"
       gitlab_rails['gitlab_email_from'] = 'gitlab@mail.test'
       gitlab_rails['gitlab_email_reply_to'] = 'noreply@mail.test'
   register: current_gitlab_rb

 - name: Restart a container
   community.docker.docker_container:
     name: gitlab
     image: gitlab/gitlab-ce
     state: started
     restart: yes
   when: current_gitlab_rb.changed or current_ipa_auth_conf.changed    

# - name: Print the gateway for each host when defined
#   ansible.builtin.debug:
#     var: ipaserver_status
#     var: ipaserver_status.stdout
#   when: (ipaserver_status.stdout | regex_findall('RUNNING') | length) == 9
