---
 - name: Create nexus container
   community.docker.docker_container:
     name: nexus
     image: sonatype/nexus3
     state: started
     domainname: "nexus.{{ domain_name }}"
     dns_servers: "{{ dns_servers }}"
     restart_policy: always
     volumes:
       - "{{ build_dir_path }}/nexus/etc:/nexus-data/etc/"
     ports:
       - "8081:8081"


# - name: Generate freeipa client yml
#   ansible.builtin.template:
#     src: "freeipa_client_gitlab.j2"
#     dest: "{{ build_dir_path }}/gitlab/config/freeipa_client.yml"
#     owner: "root"
#     group: "root"
#     mode: "0644"
#   register: current_ipa_auth_conf
#
# - name: Kostylyk(next file appears not in moment)
#   ansible.builtin.wait_for:
#     path: "{{ build_dir_path }}/gitlab/config/gitlab.rb" 
#
# - name: Add lines to gitlab config
#   ansible.builtin.blockinfile:
#     path: "{{ build_dir_path }}/gitlab/config/gitlab.rb"
#     block: |
#       gitlab_rails['ldap_enabled'] = true
#       gitlab_rails['ldap_servers'] = YAML.load_file('/etc/gitlab/freeipa_client.yml')
#   register: current_gitlab_rb
#
# - name: Restart a container
#   community.docker.docker_container:
#     name: gitlab
#     image: gitlab/gitlab-ce
#     state: started
#     restart: yes
#   when: current_gitlab_rb.changed or current_ipa_auth_conf.changed    

# - name: Print the gateway for each host when defined
#   ansible.builtin.debug:
#     var: ipaserver_status
#     var: ipaserver_status.stdout
#   when: (ipaserver_status.stdout | regex_findall('RUNNING') | length) == 9
